### ISSUE TITLE
v3.1 的 Sqlite 数据库会在指定配置数据库文件后追加 .sqlite3 后缀，导致 ThinkPHP 框架无法读取数据。

### ISSUE THREAD

**Issue by zoujingli** [top-think/think-migration#100]
## 初始化执行后的结果

安装之后读取不到数据。V3.1.x，原因是数据库文件不是一个

![image](https://github.com/top-think/think-migration/assets/4349951/4465d39f-b3c9-4dae-85ea-51669e45798c)

## 项目使用到的组件版本

![image](https://github.com/top-think/think-migration/assets/4349951/85d8a079-722e-4898-b61e-96cab027b39e)

## 项目数据库配置

![image](https://github.com/top-think/think-migration/assets/4349951/94c7fd7b-01ab-4790-a207-5a26df53e4ca)

其中 syspath 仅仅生成绝对目录。

## 使用环境
![image](https://github.com/top-think/think-migration/assets/4349951/ddc881e8-aaea-4afb-a273-7ae91ada9cbd)

## 测试脚本

通过 Composer 安装 ThinkAdmin 即可复现。

`composer create-project zoujingli/thinkadmin`

**Comment by zoujingli** [comment]
### 这个地方为什么默认要加上 .sqlite3 后缀 ?

如果 ThinkPHP 不配置 suffix 参数时，默认不追加后缀，而这里的默认追加 sqlite3 后缀，因此产生差异，就会不兼容。

**建议：** 在未配置 suffix 的情况下，建议同步使用 空，不追加后缀。


![image](https://github.com/top-think/think-migration/assets/4349951/01eaf018-cc57-4dcd-88b3-aecd6ff3eaf6)

### 经过测试，ThinkPHP 并不没有传递 suffix 过来。

![image](https://github.com/top-think/think-migration/assets/4349951/7f6d8f5a-24ed-4b65-9f8d-9729d89602f3)

对应测试版本

![image](https://github.com/top-think/think-migration/assets/4349951/2fb370e0-1fb6-4869-b21c-cb111ebe32da)

**Comment by yunwuxin** [comment]
修正了

**Comment by zoujingli** [comment]
> 修正了

什么时候可以发布正式版本？
