### ISSUE TITLE
看到 migration 尝试兼容新版的 phinx，提一个相对比较优雅的解决方案

### ISSUE THREAD

**Issue by NHZEX** [top-think/think-migration#104]
利用`php-scoper`对`phinx`的核心包进行命名空间隔离打包，我觉得操作起来会更省事，并且可以消除捆绑`cakephp`导致的全局函数污染问题，这个框架底层声明的全局函数和`tp`有冲突。

初步实验成功，代码在这个仓库：https://github.com/NHZEX/think-phinx

目录 [third-party-src](https://github.com/NHZEX/think-phinx/tree/master/third-party-src) 是原生phinx包，经过`scoper`处理后输出到 [third-party](https://github.com/NHZEX/think-phinx/tree/master/third-party)，完成捆绑发布。

执行构建的方法：
https://github.com/NHZEX/think-phinx/blob/4b816a5bfb56433f76823455011cb615315b879c/composer.json#L73-L79

cc @yunwuxin

**Comment by yunwuxin** [comment]
3.1版本已经是使用的最新版的phinx了，并且支持自动更新了

**Comment by NHZEX** [comment]
目前这种兼容方法我认为稳定性不足，容易受外部影响。同时`cakephp`污染问题是隐患 https://github.com/cakephp/phinx/issues/1647 。

不过只要还是用phinx方案，目前完美不了，只能看何时会脱钩 https://github.com/cakephp/phinx/issues/1754

**Comment by yunwuxin** [comment]
你肯定没仔细看  只是在dev的时候依赖phinx  然后把文件复制到项目中   并不会加载cakephp/phinx的依赖项
