### ISSUE TITLE
tp都6.0了，migration也3.0了，为什么不用composer安装phinx，非要一直用旧版

### ISSUE THREAD

**Issue by mygoodidea** [top-think/think-migration#30]
rt

**Comment by pifeifei** [comment]
用其他的`不可控`

比如 phinx 函数 `create($tableName, $charset, $startId)`  添加了新参数 `$startId`, 直接用的话，你根本无法操作，只能修改 phinx 包，你能及时修改吗？
如果有自己打包，我可以给他在封装一层，即使她升级，也可以正常使用，我要向切换其他同类型包，也容易，用了 tp6 的也不需要修改源码，即可平滑切换，否则你就改去吧

**Comment by mygoodidea** [comment]
@pifeifei 谢谢解答，明白了^_^

**Comment by shanezhiu** [comment]
感觉tp6跟laravel这么相似的话，干脆使用他们家的migration工具得了．
