### ISSUE TITLE
implode函数 php7.4.5支持问题

### ISSUE THREAD

**Issue by hpluso** [top-think/think-migration#42]
[think\exception\ErrorException]
implode(): Passing glue string after array is deprecated. Swap the parameters，
似乎新版php对顺序要求严格了

**Comment by shanezhiu** [comment]
不是似乎，是确实．
可参考这个issue,修复
https://github.com/phpmd/phpmd/pull/659

**Comment by ooodyn** [comment]
是不改了吗

**Comment by sunmking** [comment]
不改了，没啥人维护好像
