### ISSUE TITLE
Long text 字段类型加上进去

### ISSUE THREAD

**Issue by yulinzhihou** [top-think/think-migration#73]
用phinx的文档 ，发现 3.03用的是 **0.6.5** (Thursday, 27 October 2016) ， 感觉 有点老了。现在phinx都更新到0.13.x了。mysql也更新到8.0了。好多新功能都没办法使用了。

**Comment by ajiho** [comment]
> 用phinx的文档 ，发现 3.03用的是 **0.6.5** (Thursday, 27 October 2016) ， 感觉 有点老了。现在phinx都更新到0.13.x了。mysql也更新到8.0了。好多新功能都没办法使用了。

这边建议使用网友的拓展包：https://gitee.com/ajiho/think-phinx

**Comment by yulinzhihou** [comment]
> > 用phinx的文档 ，发现 3.03用的是 **0.6.5** (Thursday, 27 October 2016) ， 感觉 有点老了。现在phinx都更新到0.13.x了。mysql也更新到8.0了。好多新功能都没办法使用了。
> 
> 这边建议使用网友的拓展包：https://gitee.com/ajiho/think-phinx

好的，感谢。我尝试一下

**Comment by ajiho** [comment]
> > > 用phinx的文档 ，发现 3.03用的是 **0.6.5** (Thursday, 27 October 2016) ， 感觉 有点老了。现在phinx都更新到0.13.x了。mysql也更新到8.0了。好多新功能都没办法使用了。
> > 
> > 
> > 这边建议使用网友的拓展包：https://gitee.com/ajiho/think-phinx
> 
> 好的，感谢。我尝试一下

好的，其实这个包就是我弄的，有问题，可以直接联系我

**Comment by yuanzhihai** [comment]
可以用3.1版本

**Comment by zoujingli** [comment]
> 用phinx的文档 ，发现 3.03用的是 **0.6.5** (Thursday, 27 October 2016) ， 感觉 有点老了。现在phinx都更新到0.13.x了。mysql也更新到8.0了。好多新功能都没办法使用了。

phinx 高版本依赖太大了，我个人不建议直接升级，可以修改增强历史版本单独维护，大家都出份力。

**Comment by yuanzhihai** [comment]
> > 用phinx的文档 ，发现 3.03用的是 **0.6.5** (Thursday, 27 October 2016) ， 感觉 有点老了。现在phinx都更新到0.13.x了。mysql也更新到8.0了。好多新功能都没办法使用了。
> 
> phinx 高版本依赖太大了，我个人不建议直接升级，可以修改增强历史版本单独维护，大家都出份力。

我直接升级 3.1版本了

**Comment by ajiho** [comment]
为什么我看都没有人有基于[illuminate/database](https://packagist.org/packages/illuminate/database)，这个包的thinkphp6的封装呢？这个库貌似也支持数据库迁移功能的呀，希望有人封装一个，如果没人做这个事情，我非常愿意做这个事情，用think的命令行工具包装一下，用起来应该会很舒服的。

**Comment by yuanzhihai** [comment]
> 为什么我看都没有人有基于[illuminate/database](https://packagist.org/packages/illuminate/database)，这个包的thinkphp6的封装呢？这个库貌似也支持数据库迁移功能的呀，希望有人封装一个，如果没人做这个事情，我非常愿意做这个事情，用think的命令行工具包装一下，用起来应该会很舒服的。

有啊 https://github.com/yuanzhihai/think-laravel-orm

**Comment by ajiho** [comment]
> > 为什么我看都没有人有基于[illuminate/database](https://packagist.org/packages/illuminate/database)，这个包的thinkphp6的封装呢？这个库貌似也支持数据库迁移功能的呀，希望有人封装一个，如果没人做这个事情，我非常愿意做这个事情，用think的命令行工具包装一下，用起来应该会很舒服的。
> 
> 有啊 https://github.com/yuanzhihai/think-laravel-orm

你这个包是从我哪里克隆过去的。实际上问题还比较多，所以我想问问还有没有别的大佬有封装得更好的，以及这个只是基本的使用。还没有把[illuminate/database](https://packagist.org/packages/illuminate/database)包的数据库迁移功能一起封装好。我想应该找个时间把[illuminate/database]再深度集成一下。这样彻底就可以不用phinx了

**Comment by ajiho** [comment]
关于我上面封装的那个包`https://gitee.com/ajiho/think-phinx`，有主要几点问题要说明

1. 官方的数据库迁移工具，也注册了一个 和 phinx一模一样的命名空间，会导致think-phinx和官方的数据库迁移工具think-migration无法同时共存问题

```
"license": "Apache-2.0",
    "autoload": {
        "psr-4": {
            "Phinx\\": "phinx",
            "think\\migration\\": "src"
        }
    },
```

除tp官方把它的这个命名空间给去掉，或者再改成别的前缀


2. phinx本身依赖的那个数据库工具`cakephp/database`里面会有公共函数`env`会和tp框架的公共函数冲突

3. thinkphp8.0框架+你当前环境变量的php版本是8.0本身就安装不上phinx的

它的依赖和tp框架的top-think/framework的依赖产生了冲突。
```
 "require": {
        "php-64bit": ">=7.3",
        "cakephp/database": "^4.0",
        "psr/container": "^1.0 || ^2.0",
        "symfony/console": "^3.4|^4.0|^5.0|^6.0",
        "symfony/config": "^3.4|^4.0|^5.0|^6.0"
    },
```


目前phinx的仓库已经有很多人提出，想让它们把`cakephp/database`移除
phinx的维护人员应该不会同意
[issues/2217](https://github.com/cakephp/phinx/issues/2217)

**Comment by yuanzhihai** [comment]
> > > 为什么我看都没有人有基于[illuminate/database](https://packagist.org/packages/illuminate/database)，这个包的thinkphp6的封装呢？这个库貌似也支持数据库迁移功能的呀，希望有人封装一个，如果没人做这个事情，我非常愿意做这个事情，用think的命令行工具包装一下，用起来应该会很舒服的。
> > 
> > 
> > 有啊 https://github.com/yuanzhihai/think-laravel-orm
> 
> 你这个包是从我哪里克隆过去的。实际上问题还比较多，所以我想问问还有没有别的大佬有封装得更好的，以及这个只是基本的使用。还没有把[illuminate/database](https://packagist.org/packages/illuminate/database)包的数据库迁移功能一起封装好。我想应该找个时间把[illuminate/database]再深度集成一下。这样彻底就可以不用phinx了

你从哪里看出是拷贝你的？

**Comment by ajiho** [comment]
> > > > 为什么我看都没有人有基于[illuminate/database](https://packagist.org/packages/illuminate/database)，这个包的thinkphp6的封装呢？这个库貌似也支持数据库迁移功能的呀，希望有人封装一个，如果没人做这个事情，我非常愿意做这个事情，用think的命令行工具包装一下，用起来应该会很舒服的。
> > > 
> > > 
> > > 有啊 https://github.com/yuanzhihai/think-laravel-orm
> > 
> > 
> > 你这个包是从我哪里克隆过去的。实际上问题还比较多，所以我想问问还有没有别的大佬有封装得更好的，以及这个只是基本的使用。还没有把[illuminate/database](https://packagist.org/packages/illuminate/database)包的数据库迁移功能一起封装好。我想应该找个时间把[illuminate/database]再深度集成一下。这样彻底就可以不用phinx了
> 
> 你从哪里看出是拷贝你的？

[https://gitee.com/ajiho/think-laravel-orm](https://gitee.com/ajiho/think-laravel-orm)，那应该是我弄错了吧，就一眼看到README.md 是我一行一行手敲的。看起来有点眼熟，如果我说错了，请原谅。不过这些都无所谓了，只是想给开源贡献一点点自己的力量，比较长时间没用tp，想找一个更优雅的封装，因为我看了illuminate/database，这个包本身就提供数据库迁移功能那一套东西，也许研究一番，可以顺带一起把数据库迁移部分的功能也一起做了，哈哈
