### ISSUE TITLE
PHP 8.2 兼容问题，测试 PHP7、PHP8.0、PHP8.1 正常，PHP8.2 任意版本都有报错。

### ISSUE THREAD

**Issue by zoujingli** [top-think/think-migration#76]
执行 `php think migrate:run` 指令报错。

```
 Creation of dynamic property think\migration\command\migrate\Run::$adapter is deprecated
```

![image](https://user-images.githubusercontent.com/4349951/221412140-5d0faf71-1fd4-4eb0-aa26-af226056cf47.png)

**Comment by zoujingli** [comment]
已经看到有人提交了 PR，麻烦测试并合并 PR。
#75

**Comment by nishuihanlong** [comment]
测试该pr已经正常可用，但是从composer下来的think-migration是3.0.4版本还是不兼容8.2的

**Comment by liu21st** [comment]
刚发布了一版 之前没发版

**Comment by zoujingli** [comment]
v3.0.5 无法通过 composer 安装，不知道各位有没有碰到。官方源 和 aliyun 源都试了，php7.4

**Comment by liu21st** [comment]
> v3.0.5 无法通过 composer 安装，不知道各位有没有碰到。官方源 和 aliyun 源都试了，php7.4

php8.0+

**Comment by zoujingli** [comment]
![image](https://user-images.githubusercontent.com/4349951/224521184-88b7823c-4b2b-4756-96d5-fdb2a6d92272.png)
神奇，就是下载不了 😂
