### ISSUE TITLE
->addSoftDelete() 手册上有，但实际不存在！

### ISSUE THREAD

**Issue by tlerbao** [top-think/think-migration#8]
如题

**Comment by tlerbao** [comment]
还有  addTimestamps 能不能指定类型，默认是timestamp 比如想要 int(10)

**Comment by yunwuxin** [comment]
使用dev-master 版本

**Comment by yunwuxin** [comment]
上面那个 你直接创建两个int字段就是了

**Comment by yunwuxin** [comment]
刚刚release了下  等下composer update下就可以了

**Comment by tlerbao** [comment]
@yangweijie Column::float('discount') 浮点型 长度默认值怎么设置？

**Comment by yunwuxin** [comment]
参数 size  或者 length
